version: '3.7'

services:
  mycandys_products_service:
    image: mycandies/mycandys-products-service:v1.0.2
    container_name: mycandys_products_service
    ports:
      - 11082:11082
    environment:
      - PORT=${PRODUCT_SERVICE_PORT}
      - MONGODB_URI=${PRODUCT_SERVICE_MONGODB_URI}
      - AUTH_SERVICE_URL=${PRODUCT_SERVICE_AUTH_SERVICE_URL}
    networks:
      - mycandys-network

  mycandys_auth_service:
    image: mycandies/mycandys-auth-service:v1.0.0
    container_name: mycandys_auth_service
    environment:
      - APP_NAME=${AUTH_SERVICE_APP_NAME}
      - DATABASE_NAME=${AUTH_SERVICE_DATABASE_NAME}
      - DATABASE_URI=${AUTH_SERVICE_DATABASE_URI}
      - JWT_EXP=${AUTH_SERVICE_JWT_EXP}
      - JWT_REFRESH_EXP=${AUTH_SERVICE_JWT_REFRESH_EXP}
      - JWT_SECRET=${AUTH_SERVICE_JWT_SECRET}
      - PORT=${AUTH_SERVICE_PORT}
    networks:
      - mycandys-network

networks:
  mycandys-network:
    driver: bridge
