version: "3.7"

services:
  mycandys_ui:
    image: ""
  mycandys_orders_api:
    image: ""
  mycandys_products_api:
    image: ""
  mycandys_cart_api:
    image: ""
  mycandys_notification_api:
    image: ""
  mycandys_discounts_api:
    image: ""
  mycandys_auth_api:
    image: ""
  mycandys_api_gateway:
    image: ""