version: '3.7'

services:
  mycandys_ui:
    image: mycandies/mycandys-ui:latest
    container_name: mycandys-ui
    ports:
      - "11080:11080"
    environment:
      - PORT=${UI_PORT}
      - NEXT_PUBLIC_BACKEND_URL=${UI_NEXT_PUBLIC_BACKEND_URL}
      - NODE_ENV=${UI_NODE_ENV}
    networks:
      - mycandys-network
  mycandys_order_service:
    image: mycandies/mycandys-order-service:latest
    container_name: mycandys-order-service
    ports:
      - "11081:11081"
    environment:
      - PORT=${ORDER_SERVICE_PORT}
      - DATABASE_URL=${ORDER_SERVICE_MONGODB_URI}
      - DATABASE_NAME=${ORDER_SERVICE_DATABASE_NAME}
      - AUTH_SERVICE_URL=${ORDER_SERVICE_AUTH_SERVICE_URL}
      - PRODUCT_SERVICE_URL=${ORDER_SERVICE_PRODUCTS_SERVICE_URL}
      - CART_SERVICE_URL=${ORDER_SERVICE_CARTS_SERVICE_URL}
      - SWAGGER_PORT=${ORDER_SERVICE_SWAGGER_PORT}
    networks:
      - mycandys-network
  mycandys_products_service:
    image: mycandies/mycandys-products-service:v1.0.2
    container_name: mycandys-products-service
    ports:
      - 11082:11082
    environment:
      - PORT=${PRODUCTS_SERVICE_PORT}
      - MONGODB_URI=${PRODUCTS_SERVICE_MONGODB_URI}
      - AUTH_SERVICE_URL=${PRODUCTS_SERVICE_AUTH_SERVICE_URL}
      - SWAGGER_PORT=${PRODUCTS_SERVICE_SWAGGER_PORT}
    networks:
      - mycandys-network

  mycandys_carts_service:
    image: mycandies/mycandys-carts-service:v1.0.2
    container_name: mycandys-carts-service
    environment:
      - PORT=${CARTS_SERVICE_PORT}
      - MONGODB_URI=${CARTS_SERVICE_MONGODB_URI}
      - AUTH_SERVICE_URL=${CARTS_SERVICE_AUTH_SERVICE_URL}
      - PRODUCT_SERVICE_URL=${CARTS_SERVICE_PRODUCTS_SERVICE_URL}
      - SWAGGER_PORT=${CARTS_SERVICE_SWAGGER_PORT}
    networks:
      - mycandys-network

  mycandys_auth_service:
    image: mycandies/mycandys-auth-service:v1.0.0
    container_name: mycandys-auth-service
    ports:
      - 11089:11089
    environment:
      - APP_NAME=${AUTH_SERVICE_APP_NAME}
      - DATABASE_NAME=${AUTH_SERVICE_DATABASE_NAME}
      - DATABASE_URI=${AUTH_SERVICE_DATABASE_URI}
      - JWT_EXP=${AUTH_SERVICE_JWT_EXP}
      - JWT_REFRESH_EXP=${AUTH_SERVICE_JWT_REFRESH_EXP}
      - JWT_SECRET=${AUTH_SERVICE_JWT_SECRET}
      - PORT=${AUTH_SERVICE_PORT}
      - SPRING_PROFILE=${AUTH_SERVICE_SPRING_PROFILE}
      - SWAGGER_SERVER_URL=${AUTH_SERVICE_SWAGGER_SERVER_URL}
    networks:
      - mycandys-network

  mycandys_gateway_service:
    image: mycandies/mycandys-gateway-service:v1.0.0
    container_name: mycandys-gateway-service
    ports:
      - 11088:11088
    environment:
      - PORT=${GATEWAY_SERVICE_PORT}
      - AUTH_SERVICE_URI=${GATEWAY_SERVICE_AUTH_SERVICE_URI}
    networks:
      - mycandys-network

networks:
  mycandys-network:
    driver: bridge
