version: '3.7'

services:
  mycandys_products_service:
    image: mycandies/mycandys-products-service:v1.0.2
    container_name: mycandys_products_service
    ports:
      - 11082:11082
    env_file:
      - mycandys-products-service.env
    networks:
      - mycandys-network

  mycandys_auth_service:
    image: mycandies/mycandys-auth-service:v1.0.0
    container_name: mycandys_auth_service
    env_file:
      - mycandys-auth-service.env
    networks:
      - mycandys-network

networks:
  mycandys-network:
    driver: bridge
